# Generated by Django 3.1 on 2020-08-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='auction',
        ),
    ]
