# Generated by Django 3.1 on 2020-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidprice',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
