# Generated by Django 3.1 on 2020-09-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200902_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingbids',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
